### ISSUE TITLE
VboxManage: error

### ISSUE THREAD

**Issue by jinxun97** [archanchoudhury/Cuckoo-Script#2]
Error while run `vmcloak init --verbose --win7x64 win7x64base --cpus 2 --ramsize 2048`

`0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Failed to create medium
VBoxManage: error: Could not create the medium storage unit '/home/cuck/.vmcloak/image/win7x64base.vdi'.
VBoxManage: error: VDI: cannot create image '/home/cuck/.vmcloak/image/win7x64base.vdi' (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium
VBoxManage: error: Context: "RTEXITCODE handleCreateMedium(HandlerArg*)" at line 450 of file VBoxManageDisk.cpp
ERROR:vmcloak.vm:[-] Error running command: Command '['/usr/bin/VBoxManage', 'createhd', '--size', '262144', '--filename', '/home/cuck/.vmcloak/image/win7x64base.vdi']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/cuck/.virtualenvs/cuckoo-test/bin/vmcloak", line 8, in <module>
    sys.exit(main())
  File "/home/cuck/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/cuck/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/cuck/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cuck/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cuck/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cuck/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/vmcloak/main.py", line 265, in init
    m.create_hd(hdd_path, hddsize * 1024)
  File "/home/cuck/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/vmcloak/vm.py", line 100, in create_hd
    self._call("createhd", filename=hdd_path, size=fsize)
  File "/home/cuck/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/vmcloak/vm.py", line 41, in _call
    raise CommandError
vmcloak.exceptions.CommandError
`
![image](https://user-images.githubusercontent.com/59555895/144745754-323d3e53-8762-4cd4-bde7-5387417494b1.png)

**Comment by archanchoudhury** [comment]
It looks like the vdi file is already present in your directory. Did you
run the command previously? If so it will not allow you to override.

Go to your working directory then .vmcloak and check each parent directory
and remove all previously created file. You should only have the iso image,
nothing else in that location.

Once you remove all other files, rerun the command. Make sure, you have
enough ram, CPU given to the base VM and virtualization options are ticked
in processor settings. It will run smoothly.

**Comment by jinxun97** [comment]
It works but is it normal to run `vmcloak init --verbose --win7x64 win7x64base --cpus 2 --ramsize 2048` while staying at  `INFO:vmcloak:Starting the Virtual Machine u'win7x64base' to install Windows.` for already 2 hours ++ and still running.
![image](https://user-images.githubusercontent.com/59555895/144756583-39669b36-f586-4f15-954c-4188be8d521f.png)

Below are my Ubuntu VM properties & Host Machine spec.
![image](https://user-images.githubusercontent.com/59555895/144756417-0b8f6e9b-7f22-46aa-9798-ff6a2599839b.png)
![image](https://user-images.githubusercontent.com/59555895/144756522-27a7d5c8-6afc-4505-b1fd-867247a9f58c.png)

**Comment by archanchoudhury** [comment]
Yes it is normal. For me it took overnight. I started the script and
checked back in morning. Not sure, when it was finished. So we need to be
patient while doing this. This is the most time consuming step. Next, the
snapshot and other stuffs will also take time, but will be comparatively
quicker.
Once done, make sure to check the config files and make adjustments as
explained.

**Comment by jinxun97** [comment]
@archanchoudhury Please help me again 😢 A connection error result shown after running `vmcloak install win7x64cuckoo ie11` . 

![image](https://user-images.githubusercontent.com/59555895/144763000-8df58dce-5d9f-4ae9-a2e0-0ec885957965.png)
Error Message 
  File "/home/cuck/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.56.2', port=8000): Max retries exceeded with url: /store (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7d53e827d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by archanchoudhury** [comment]
Looks the network connection issue. The connection is not getting
established due to the fact of max api request to the url.

Try below to solve the issue-
1. Check your VM is having a live internet connection.
2. Reboot the VM to flush the cache dns and start back.
3. Try with some other packages like firefox instead of ie11.
